# GET https://api.zoom.us/v2/chat/channels/9ee61cba546442d49d357331af0f2e88
# Authorization: Bearer eyJhbGciOiJIUzUxMiIsInYiOiIyLjAiLCJraWQiOiJhMWE1NGVmNi1hNzczLTQ4NjgtODgxYy1hMjgyZGY1MmEyMDQifQ.eyJ2ZXIiOjcsImF1aWQiOiI4OTkxZDQxNjIwNjQzY2RkMzFlNzZmMzA1MjVkMmY0MiIsImNvZGUiOiJWN3pRZFlwWFJCaW4zTVA4WFctTHp3R3B3N0duRVNTZVkiLCJpc3MiOiJ6bTpjaWQ6a3VKQlVhUkVUUW1KT0d3c1hmRGNwdyIsImdubyI6MCwidHlwZSI6MywiYXVkIjoiaHR0cHM6Ly9vYXV0aC56b29tLnVzIiwidWlkIjoiSmpZRE5rZ09TUGUxVk1lZmZVU0ptZyIsIm5iZiI6MTY2OTU3NzU3MCwiZXhwIjoxNjY5NTgxMTcwLCJpYXQiOjE2Njk1Nzc1NzAsImFpZCI6Ik5KSC1Fek53UTlLZmlPQUhzUnpKTXciLCJqdGkiOiJhYzY2ODc5MS1iZmE4LTRjNmEtOGYwOC02MjFkZjhmYzYzMmMifQ.zKPwDhFIhIpvEabGm7z95DJC30mBD2b0VvoyqgE7XklwhCTHh63WR_5RVX0h1VqQdLhw7jKOn4o3AFz7ZS4Igg

GET http://localhost:8080/api/message/channels
